#!/bin/bash
# Definir variables para colores de texto
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
PURPLE='\033[1;35m'
CYAN='\033[1;36m'
GRAY='\033[1;37m'
WHITE='\033[1;37m'
# Definir variables para colores de fondo
BG_RED='\033[0;41m'
BG_GREEN='\033[0;42m'
BG_YELLOW='\033[0;43m'
BG_BLUE='\033[0;44m'
BG_PURPLE='\033[0;45m'
BG_CYAN='\033[0;46m'
BG_GRAY='\033[0;47m'
# Resetear colores
RESET='\033[0m'
clear
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -e "${YELLOW}WAIT -"
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -e "${YELLOW}WAIT -"
done
echo -e "${GREEN}OK !"
tput cnorm
}
clear
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ───────────────── /// ────────────────── ${YELLOW}"
figlet -p -f slant SlowDNS
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ────────────── Installer ─────────────── ${YELLOW}"
echo -e ""
echo -e "      This script will do the installation"
echo -e "      for SlowDNS connection mode."
echo -e ""
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ───────────────── /// ────────────────── ${YELLOW}"
echo ""
echo -e "DOWLOADING DEPENDENCIES..."
echo ""
fun_att () {
apt install ncurses-utils -y
mkdir /etc/slowdns
cd /etc/slowdns
wget https://github.com/powermx/dnstt/raw/main/dns-server; chmod +x dns-server
wget https://raw.githubusercontent.com/powermx/dnstt/main/remove-slow; chmod +x remove-slow
wget https://raw.githubusercontent.com/powermx/dnstt/main/slowdns-info; chmod +x slowdns-info
wget https://raw.githubusercontent.com/powermx/dnstt/main/slowdns-drop; chmod +x slowdns-drop
wget https://raw.githubusercontent.com/powermx/dnstt/main/slowdns-ssh; chmod +x slowdns-ssh
wget https://raw.githubusercontent.com/powermx/dnstt/main/slowdns-ssl; chmod +x slowdns-ssl
wget https://raw.githubusercontent.com/powermx/dnstt/main/slowdns-socks; chmod +x slowdns-socks
wget https://raw.githubusercontent.com/powermx/dnstt/main/slowdns-customservice; chmod +x slowdns-customservice
wget -qO /bin/slowdns https://raw.githubusercontent.com/powermx/dnstt/main/slowdns && chmod +x /bin/slowdns
wget https://raw.githubusercontent.com/powermx/dnstt/main/stopdns; chmod +x stopdns
}
fun_bar 'fun_att'
echo -e "CONFIGURING FIREWALL..."
echo ""
fun_ports () {
apt install firewalld -y && sudo firewall-cmd --zone=public --permanent --add-port=80/tcp && sudo firewall-cmd --zone=public --permanent --add-port=8080/tcp && sudo firewall-cmd --zone=public --permanent --add-port=443/tcp && sudo firewall-cmd --zone=public --permanent --add-port=85/tcp && sudo firewall-cmd && sudo firewall-cmd --zone=public --permanent --add-port=53/udp && sudo firewall-cmd --zone=public --permanent --add-port=5300/udp && sudo firewall-cmd && sudo firewall-cmd --zone=public --permanent --add-port=2222/tcp && sudo firewall-cmd --reload
}
fun_bar 'fun_ports'
echo -e "SETTING CLOUDFLARE DNS..."
echo ""
fun_dnscf () {
sudo systemctl disable systemd-resolved.service && sudo systemctl stop systemd-resolved.service && sudo mv /etc/resolv.conf /etc/resolv.conf.bkp && echo "nameserver 1.1.1.1" > /etc/resolv.conf
sudo systemctl enable systemd-resolved.service && sudo systemctl start systemd-resolved.service
sleep 2
}
fun_bar 'fun_dnscf'
clear
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ───────────────── /// ────────────────── ${YELLOW}"
figlet -p -f slant SlowDNS
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ────────────── Installer ─────────────── ${YELLOW}"
echo ""
echo -e "          \033[1;33mINSTALLATION COMPLETED!\033[0m          "
echo ""
echo -e "To open the menu, use the command: ${RED}slowdns${RESET}"
cd
sleep 3
echo -e "\033[1;31mPRESS ENTER TO CONTINUE\033[0m"
read -p " "
slowdns
