#!/bin/bash
# Definir variables para colores de texto
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
PURPLE='\033[1;35m'
CYAN='\033[1;36m'
GRAY='\033[1;37m'
WHITE='\033[1;37m'
# Definir variables para colores de fondo
BG_RED='\033[0;41m'
BG_GREEN='\033[0;42m'
BG_YELLOW='\033[0;43m'
BG_BLUE='\033[0;44m'
BG_PURPLE='\033[0;45m'
BG_CYAN='\033[0;46m'
BG_GRAY='\033[0;47m'
# Resetear colores
RESET='\033[0m'
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ───────────────── /// ────────────────── ${YELLOW}"
figlet -p -f slant SlowDNS
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ─────────────── SlowDNS ──────────────── ${YELLOW}"
echo -e "${GREEN}SlowDNS Info!"
echo ""
echo -ne "${YELLOW}YOUR NS: ${WHITE} " && cat /etc/slowdns/infons
echo -ne "${YELLOW}YOUR PUBLIC KEY:\033[0m " && cat /root/server.pub
echo ""
echo -e "${YELLOW}YOUR KEY is saved in the file /root/server.pub\033[0m"
echo -e "${YELLOW}Keep it in a safe place, you may need it in the future!${YELLOW}"
echo ""
echo -e "\033[1;33m › PRESS ENTER TO CONTINUE\033[0m"
read -p " "
slowdns
